import {calc,type Model} from './engine';
import {experience} from './experience';
import {input,button,help,esc,money,fmt} from './views';
import {lowerPrice,activeAssumptions,pricingMessage,type ReportContext} from './insights';
export function glanceShell(m:Model,aux:Record<string,string>){return `<div class="summary-card glance-card"><h2 class="eyebrow">Your order at a glance</h2><div id="glance-metrics"></div><div id="glance-status"></div><div id="glance-breakdown"></div><div id="glance-minimum"></div>
 <details id="glance-pricing" class="glance-disclosure pricing-disclosure"><summary>Help me set my price <span aria-hidden="true">＋</span></summary><div class="glance-panel">${input('Target margin after selling expenses','target',m.target,{unit:'%',help:'Target margin',hint:'The percentage of your selling price you want left before overhead, financing and taxes.'})}<div id="price-suggestion"></div></div></details>
 <details id="glance-order" class="glance-disclosure"><summary>See the whole-order estimate</summary><div class="glance-panel"><div class="glance-panel-title">At full sell-through ${help('Whole-order estimate')}</div><div id="glance-order-result"></div></div></details>
 <details id="glance-lower" class="glance-disclosure"><summary>What if I sell for less?</summary><div class="glance-panel"><p id="quick-assumption" class="help-text"></p>${input('Alternative selling price','aux.quickPrice',lowerPrice(m,aux.quickPrice).alternative,{unit:'₦',help:'Lower-price comparison',hint:'A comparison only. Your selling price stays unchanged.'})}<div id="glance-lower-result"></div>${button('Compare other changes','comparechanges','link-button')}</div></details>
 <div id="glance-assumptions"></div><div class="glance-links">${button('See all costs','allcosts','link-button')}<a href="#cash-details" data-action="cash">See cash needed and recovery ↓</a></div></div>`;}
function rows(values:[string,string][],label:string){return `<table class="glance-table" aria-label="${label}"><tbody>${values.map(([k,v],i)=>`<tr class="${i===values.length-1?'total-row':''}"><th scope="row">${k}</th><td>${v}</td></tr>`).join('')}</tbody></table>`;}
export function updateGlance(m:Model,aux:Record<string,string>){const r=calc(m),sale=r.salesValid&&r.contribution!==null,negative=sale&&r.contribution!.lt(0),provisional=r.missing.length>0;
 const put=(id:string,html:string)=>{document.getElementById(id)!.innerHTML=html};
 put('glance-metrics',`<div class="metric primary-metric"><div class="metric-label">Cost per sellable item ${help('Cost per sellable item')}</div><strong>${r.landingValid?money(r.cost):'Add your order details'}</strong><p>To buy and land each item you expect to sell.${r.landingValid&&r.recovery.gt(0)?' Excludes import tax you marked as recoverable.':''}</p></div>
 <div class="metric primary-metric ${negative?'loss-metric':''}"><div class="metric-label">${negative?'Loss per sale':'What each sale leaves you'} ${help('What each sale leaves you')}</div><strong>${sale?money(negative?r.contribution!.abs():r.contribution):m.price?'Not available':'Add a selling price'}</strong><p>${negative?'Each sale leaves you short before overhead and taxes.':'After import and selling expenses.'}</p><p class="result-note">Before overhead, financing and business taxes.</p></div>${sale?`<div class="margin-line">Margin after selling expenses ${help('Margin after selling expenses')}<strong>${fmt(r.margin,'%')}</strong></div>`:''}`);
 put('glance-status',r.landingValid?`<div class="completeness ${provisional?'incomplete':''}"><strong>${provisional?'Estimate with missing costs':'All selected costs included.'}</strong>${provisional?'<p>Some costs are still missing. Your estimate may change when you add them.</p>'+button('See missing costs','missing','link-button'):''}</div>`:`<p class="empty-note">${m.q||m.total||m.unit?'Correct the highlighted order details to update your estimate.':'Add your order details to get started.'}</p>`);
 put('glance-breakdown',sale?rows([['Selling price',money(r.p)],['Cost to buy and land it','−'+money(r.cost.abs())],['Selling expenses','−'+money(r.variable!.abs())],[negative?'Shortfall per sale':'Left before overhead and taxes',money(negative?r.contribution!.abs():r.contribution)]],'Where your selling price goes'):`<p class="glance-empty">${!m.price?'Add a selling price to see what each sale leaves you.':'Add valid order and selling details to see where your selling price goes.'}</p>`);
 const pm=pricingMessage(m);put('glance-minimum',pm?`<p class="minimum-note">${esc(pm)}</p>`:`<div class="minimum-note"><span>${provisional?'Provisional minimum based on entered costs':'Minimum price to cover item and selling costs'} ${help('Minimum price')}</span><strong>${money(r.zeroPrice)}</strong><small>Below this price, each sale loses money before overhead and taxes.${provisional?' This may rise when missing costs are added.':''}</small></div>`);
 put('price-suggestion',pm?`<p class="helper-message">${esc(pm)}</p>`:!m.target.trim()?'<p class="help-text">Enter your own target margin to see a suggested price.</p>':r.errors.target?`<p class="helper-message">${esc(r.errors.target)}</p>`:!r.targetPrice?'<p class="helper-message">Percentage selling fees plus your target margin leave no room to cover item costs. No finite suggested price is available.</p>':`<div class="suggested-price"><p>${provisional?'Provisional: ':''}For a ${esc(m.target)}% margin, sell at <strong>${money(r.targetPrice)}</strong>.</p>${button('Use this price','applyprice','primary')}<p class="help-text">Before overhead, financing and business taxes.${provisional?' Based on entered costs; add missing costs before relying on this price.':''}</p></div>`);
 put('glance-order-result',sale?`<p>${provisional?'Provisional estimate. ':''}If all ${esc(m.s)} items sell at these figures, the order ${negative?'has a '+money(r.batch!.abs())+' shortfall':'leaves '+money(r.batch)} before overhead, financing and taxes.</p><p class="help-text">Assumes the selling price and expenses stay unchanged.</p>`:'<p>Add valid order details and a selling price to estimate the whole order.</p>');
 const quick=lowerPrice(m,aux.quickPrice);const qi=document.querySelector<HTMLInputElement>('[data-key="aux.quickPrice"]')!;if(aux.quickPrice===undefined)qi.value=quick.alternative;
 document.getElementById('quick-assumption')!.textContent=aux.quickPrice===undefined?'Starts at 10% below your current price. Edit it to test another price.':'You entered this comparison price. It is not applied to your order.';
 const quickInvalid=!!quick.error&&aux.quickPrice!==undefined;qi.setAttribute('aria-invalid',String(quickInvalid));const error=qi.closest('.field')!.querySelector<HTMLElement>('.error')!;error.hidden=!quickInvalid;error.textContent=quickInvalid?quick.error:'';
 put('glance-lower-result',!sale?'<p>Add valid order details and a selling price to compare.</p>':quick.error?`<p class="helper-message">${esc(quick.error)}</p>`:quick.result?.salesValid&&quick.result.contribution&&quick.difference?rows([['Current selling price',money(r.p)],['Alternative selling price',money(quick.result.p)],['Current contribution per sale',money(r.contribution)],['Alternative contribution per sale',money(quick.result.contribution)],['Difference per sale',(quick.difference.gt(0)?'+':quick.difference.lt(0)?'−':'')+money(quick.difference.abs())]],'Lower-price comparison')+`<p>${provisional?'Based on entered costs, ':''}at ${money(quick.result.p)} per item, each sale ${quick.result.contribution.lt(0)?'leaves you short by '+money(quick.result.contribution.abs()):'leaves '+money(quick.result.contribution)} before overhead and taxes.</p>`:'<p>Correct the alternative price to compare.</p>');
 const notes=activeAssumptions(m);put('glance-assumptions',notes.length?`<ul class="assumption-preview">${notes.slice(0,2).map(n=>'<li>'+esc(n)+'</li>').join('')}</ul>${button('See assumptions','assumptions','link-button')}`:button('See assumptions','assumptions','link-button'));
}
export function quickContext(aux:Record<string,string>,selected:boolean):ReportContext{return selected?{alternativePrice:aux.quickPrice}:{};}
