import Decimal from 'decimal.js';
import {config,track} from './config';
import {calc,scenario,stress,shipping,validateImport,num,row,categories,type Model,type Scenario} from './engine';
import {fresh,illustrative,initialise,experience,freight,other,updateQuantity,switchCosts,switchSelling,otherSubtotal,inclusionGroups,overlap,SIMPLE_OTHER_ID,safeNum,combined,scopedScenario} from './experience';
import {page,input,select,button,help,helpCopy,esc,money,fmt} from './views';
import {summary,table,resultValues,printReport} from './reports';
import {glanceShell,updateGlance,quickContext} from './glance';
import {activeAssumptions} from './insights';
import {assumptions} from './reports';
import {excelReport} from './excel';
import './style.css';
let model=fresh();
const aux:Record<string,string>={};
const touched=new Set<string>(),openDetails=new Set(['step-1']);
const app=document.querySelector<HTMLElement>('#app')!;
let suggested=false,message='',storageError='',exampleEdited=false;
const builtIn=()=>combined(model);
let saves:{id:string;input:Model}[]=[];
try{const parsed=JSON.parse(localStorage.getItem('zolan-saves-v1')||'[]');if(!Array.isArray(parsed))throw Error();saves=parsed.map((x:{id:string;input:unknown})=>({id:String(x.id),input:initialise(validateImport(x.input))}));}catch{storageError='Saved calculations could not be read. Download an Excel report to keep a copy of your figures.'}
const state=()=>experience(model);
const result=()=>calc(model);
function notify(text:string){message=text;const el=document.querySelector('#notice');if(el)el.textContent=text;}
function rebuild(focusKey?:string){
 const current=app.querySelector<HTMLInputElement>(':focus');const key=focusKey||current?.dataset.key;
 for(const d of app.querySelectorAll<HTMLDetailsElement>('details[id]')){if(d.open)openDetails.add(d.id);else openDetails.delete(d.id)}
 app.innerHTML=page(model,aux);
 document.querySelector('#summary')!.innerHTML=glanceShell(model,aux);
 for(const d of app.querySelectorAll<HTMLDetailsElement>('details[id]'))d.open=openDetails.has(d.id);
 document.querySelector('#notice')!.textContent=message||storageError;
 renderScenarioEditors();refresh();
 if(key){const field=Array.from(app.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-key]')).find(el=>el.dataset.key===key&&!el.disabled);field?.focus()}
}
function metric(label:string,value:string,note='',primary=false){return `<div class="metric ${primary?'primary-metric':''}"><div class="metric-label">${label}${help(label==='Loss per sale'?'What each sale leaves you':label)}</div><strong>${value}</strong><p>${note}</p></div>`}
function refresh(){
 const r=result(),started=!!(model.q.trim()||model.total.trim()||model.unit.trim()),valid=r.landingValid;
 const sell=r.salesValid&&r.contribution!==null;
 const negative=sell&&r.contribution!.lt(0);
 const provisional=r.missing.length>0;
 updateGlance(model,aux);
 document.querySelector('#supplier-subtotal')!.textContent=!model.q||!['q','total','unit','cny','usd','supplierCny','supplierUsd','fee','feePct'].every(k=>!r.errors[k])?'':`Supplier cost per item: ${money(r.payment.div(num(model.q)))}. Before shipping and import costs.`;
 const cash=valid?money(r.cash):'Add valid order details';
 document.querySelector('#cash-results')!.innerHTML=`<div class="secondary-grid">${metric('Cash needed for this shipment',cash,'To buy and get the goods to your location.')}${metric('Sales to recover shipment cash',r.salesValid&&r.units!==null?r.units.toString()+' sales':'Add a selling price','After setting aside selling expenses.')}</div><p class="help-text">Assumes customers pay immediately. Excludes overhead, financing and other cash payments. No restocking is assumed.</p>${r.salesValid&&r.units!==null&&!r.achievable?`<p class="missing-note">This batch cannot recover the shipment cash at these figures. Full-batch shortfall: ${money(r.shortfall)}.</p>`:''}${r.recoveryMonths?`<p><strong>Approximate recovery time</strong><br>About ${fmt(r.recoveryMonths)} months at ${esc(model.monthly)} sales per month.</p>`:''}${!model.planning?`<p class="help-text">Add expected monthly sales in the business-cost plan to estimate recovery time.</p>`:''}`;
 document.querySelector('#cost-results')!.innerHTML=`<p class="help-text">Supplier payment + active shipment costs = upfront cash. Subtract confirmed recoverable tax for economic inventory cost, then divide by sellable items. Inactive entries are retained and excluded.</p>${table(model)}${r.missing.length?`<p class="missing-note">Missing costs: ${r.missing.map(esc).join(', ')}.</p>`:''}`;
 document.querySelector('#more-results-content')!.innerHTML=valid?`<div class="secondary-grid">${resultValues(model).filter(([label])=>['Gross profit per sale','Gross margin','Markup','Full-batch contribution','Potential recoverable import tax','Economic landed inventory cost','Minimum price to cover item and selling costs'].includes(label)).map(([k,v])=>`<div class="secondary-result"><span>${k}</span><strong>${v}</strong></div>`).join('')}</div><p class="help-text">Gross profit subtracts inventory cost. What each sale leaves you also subtracts selling expenses. Fixed business costs are separate.</p>`:'<p class="empty-note">Add valid order details to see more results.</p>';
 document.querySelector('#planning-results')!.innerHTML=model.planning?`<div class="secondary-grid"><div class="secondary-result"><span>Forecast sales in this period</span><strong>${r.planningValid&&r.forecast?r.forecast.toString():'Add valid planning details'}</strong></div><div class="secondary-result"><span>Estimated operating result</span><strong>${r.planningValid?money(r.operating):'Not available'}</strong></div><div class="secondary-result"><span>Operating break-even ${help('Operating break-even')}</span><strong>${r.planningValid&&r.breakEven!==null?r.breakEven.toString()+' sales':'Not achievable at these figures'}</strong></div></div><p class="help-text">Forecast sales are capped at sellable stock. This is a single-product planning estimate before financing and business taxes. Shipment cash recovery and operating break-even answer different questions.</p>`:'';
 const supplierInput=app.querySelector<HTMLInputElement>('[data-key="total"]');if(supplierInput?.readOnly)supplierInput.value=r.errors.unit||r.errors.cny||r.errors.usd||r.errors.supplierCny||r.errors.supplierUsd?'':r.payment.toFixed(2);
 const otherInput=app.querySelector<HTMLInputElement>('[data-key="display.other"]');if(otherInput)otherInput.value=otherSubtotal(model).toFixed(2);
 const sellingInput=app.querySelector<HTMLInputElement>('[data-key="display.selling"]');if(sellingInput)sellingInput.value=r.variable?.toFixed(2)||r.fixed.toFixed(2);
 const shippingInput=app.querySelector<HTMLInputElement>('[data-key="display.shipping"]');if(shippingInput)shippingInput.value=r.trace.find(t=>t.id===freight(model).id)?.ngn||'';
 const ov=document.querySelector('#overlap-review');if(ov)ov.innerHTML=overlap(model)?`<div class="overlap-panel"><strong>Check these costs for overlap</strong><p>Your shipping quote includes other charges, and you also entered another-cost total. Review the total before using these results.</p><div class="actions">${button('Remove the overlapping amount','removeoverlap','secondary')}${button('Replace with costs outside the quote','replaceoverlap','secondary')}${button('Open a detailed breakdown','reviewdetails','link-button')}</div></div>`:state().overlapResolved?'<p class="help-text">You confirmed the remaining other costs are outside this shipping quote.</p>':'';
 document.querySelector<HTMLElement>('#zolan-cta')!.hidden=!valid;
 updateHelpers();updateScenarioResults();showErrors();
 updateReport();
}
function reportContext(){return quickContext(aux,!!document.querySelector<HTMLDetailsElement>('#glance-lower')?.open)}
function updateReport(){const report=document.querySelector('#print-report');if(report)report.innerHTML=result().landingValid?printReport(model,reportContext()):'<p>Add valid order details before printing.</p>';}
function errorKey(key:string){const r=model.rows.find(x=>key===x.id||key===x.id+'base'||key===x.id+'customsRate'||key===x.id+'recover');if(r){const i=model.rows.indexOf(r);return `rows.${i}.`+(key.endsWith('customsRate')?'customsRate':key.endsWith('recover')?'recover':key.endsWith('base')?'note':'amount')}if(/^sell\d+$/.test(key))return 'selling.'+key.slice(4)+'.amount';if(/^pct\d+$/.test(key))return 'selling.'+key.slice(3)+'.pct';if(key==='sellingTotal')return 'experience.sellingTotal';return key}
function showErrors(){const r=result();const mapped=new Map(Object.entries(r.errors).map(([k,v])=>[errorKey(k),v]));
 for(const field of app.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-key]')){const key=field.dataset.key!;if(key==='aux.quickPrice')continue;const value=touched.has(key)?mapped.get(key):undefined;field.setAttribute('aria-invalid',String(!!value));const wrapper=field.closest('.field'),error=wrapper?.querySelector<HTMLElement>('.error');if(error){error.hidden=!value;error.textContent=value||''}}
 for(const el of app.querySelectorAll<HTMLElement>('[id^="rowerr-"]')){const key=el.id.slice(7),i=model.rows.findIndex(x=>x.id===key);const msg=Object.entries(r.errors).filter(([k])=>k.startsWith(key)).map(([,v])=>v).join(' ');el.hidden=!msg||![...touched].some(k=>k.startsWith('rows.'+i+'.'));el.textContent=msg;}
}
function getPath(path:string){let o:any=model;for(const part of path.split('.'))o=o?.[part];return o}
function setPath(path:string,value:unknown){const p=path.split('.');let o:any=model;for(const part of p.slice(0,-1))o=o[part];o[p.at(-1)!]=value}
function changeValue(el:HTMLInputElement|HTMLSelectElement){const key=el.dataset.key;if(!key||key.startsWith('display.'))return;const value=el instanceof HTMLInputElement&&el.type==='checkbox'?el.checked:el.value;
 if(key.startsWith('aux.')){aux[key.slice(4)]=String(value);if(key==='aux.quickPrice'){updateGlance(model,aux);updateReport()}else updateHelpers();return}
 if(key.startsWith('builtIn.')){(builtIn() as any)[key.slice(8)]=value;updateScenarioResults();return}
 if(key==='q'){updateQuantity(model,String(value));for(const field of app.querySelectorAll<HTMLInputElement>('[data-key="s"]'))field.value=model.s}
 else if(key==='allin'){model.mode=value?'allin':'separate';state().foreignMode=model.mode as 'allin'|'separate';}
 else if(key==='saveName'||key==='replacement')return;
 else{setPath(key,value);if(/^rows\.\d+\.amount$/.test(key)&&el.value.trim()){const cost=model.rows[Number(key.split('.')[1])];if(cost.status==='unknown')cost.status='estimate';if(cost.id===SIMPLE_OTHER_ID)state().overlapResolved=false;}}
 if(key==='experience.sellingTotal'&&String(value).trim())state().sellingStatus='entered';
 if(key==='experience.sellableAdjusted'&&!value)model.s=model.q;
 if(key==='experience.feeEnabled'&&!value&&model.mode==='separate'){/* fee values remain retained */}
 if(model.illustrative)exampleEdited=true;
 mirror(key,value,el);refresh();
}
function mirror(key:string,value:unknown,source:HTMLElement){for(const field of app.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-key]'))if(field!==source&&field.dataset.key===key){if(field instanceof HTMLInputElement&&field.type==='checkbox')field.checked=!!value;else field.value=String(value)}
 // statuses may change automatically when an amount is typed
 for(const el of app.querySelectorAll<HTMLSelectElement>('select[data-key]')){if(el.dataset.key?.endsWith('.status'))el.value=String(getPath(el.dataset.key));if(el.dataset.key==='experience.sellingStatus')el.value=state().sellingStatus;}}
app.addEventListener('input',event=>{const target=event.target;if(target instanceof HTMLInputElement&&target.dataset.key&&target.type!=='checkbox')changeValue(target)});
app.addEventListener('change',event=>{const target=event.target;if((target instanceof HTMLSelectElement||target instanceof HTMLInputElement)&&target.dataset.key){changeValue(target);touched.add(target.dataset.key);if(target instanceof HTMLSelectElement||target.type==='checkbox'){const focus=target.dataset.key;rebuild(focus)}else showErrors();return}
 if(target instanceof HTMLInputElement){if(target.dataset.group){const group=inclusionGroups.find(x=>x.label===target.dataset.group)!;const f=freight(model);f.includes=target.checked?[...new Set([...f.includes,...group.categories])]:f.includes.filter(c=>!group.categories.includes(c));state().overlapResolved=false;rebuild();}
 if(target.dataset.ref||target.dataset.include){const cost=model.rows.find(r=>r.id===(target.dataset.ref||target.dataset.include))!;const key=target.dataset.ref?'refs':'includes';cost[key]=target.checked?[...new Set([...cost[key],target.value])]:cost[key].filter(x=>x!==target.value);state().overlapResolved=false;rebuild();}}});
app.addEventListener('focusout',event=>{const target=event.target;if((target instanceof HTMLInputElement||target instanceof HTMLSelectElement)&&target.dataset.key){touched.add(target.dataset.key);showErrors()}});
app.addEventListener('toggle',event=>{const el=event.target;if(el instanceof HTMLDetailsElement&&el.id){if(el.id==='glance-lower')updateReport();if(el.open)openDetails.add(el.id);else openDetails.delete(el.id)}},true);
app.addEventListener('click',event=>{const target=event.target as HTMLElement;const helpButton=target.closest<HTMLElement>('[data-help]');if(helpButton){openHelp(helpButton);return}const b=target.closest<HTMLElement>('[data-action]');if(b){event.preventDefault();void action(b.dataset.action!);}});
function updateHelpers(){
 const e=state();const shippingEl=document.querySelector('#shipping-estimate');if(shippingEl){try{const h=shipping(e.helperMode,e.helper);shippingEl.innerHTML=`${h.weight.toFixed(4)} ${h.unit} · ${money(h.amount)}${e.appliedHelper&&e.appliedHelper!==JSON.stringify({mode:e.helperMode,input:e.helper})?'<p>Estimate changed. Choose “Use this estimate” to update shipping. Your current quote has been kept.</p>':''}`}catch{shippingEl.textContent='Add the provider’s weight or size figures to see an estimate.'}}
 const ads=document.querySelector('#ads-estimate');if(ads){try{const sales=num(aux.adsSales||'',true);if(!sales.isInteger()||sales.lte(0))throw Error();ads.textContent='Advertising per sale: '+money(num(aux.adsSpend||'',true).div(sales))}catch{ads.textContent=aux.adsSales==='0'?'Enter completed sales above zero.':'Enter spend and completed sales to see an estimate.'}}
 const returns=document.querySelector('#returns-estimate');if(returns){try{const p=num(aux.returnProb||'',true);if(p.gt(100))throw Error();returns.textContent='Average return expense per sale: '+money(p.div(100).mul(num(aux.returnCost||'',true)))}catch{returns.textContent='Enter a return rate from 0 to 100% and the net cost per return.'}}
 const loss=document.querySelector('#loss-suggestion');if(loss){try{const p=num(aux.loss||'',true);if(p.gte(100))throw Error();loss.textContent='Rounded down to '+num(model.q,true).mul(new Decimal(1).sub(p.div(100))).floor()+' sellable items.'}catch{loss.textContent='Enter a damage percentage below 100%.'}}
}
function renderScenarioEditors(){const el=document.querySelector('#scenario-editors')!;el.innerHTML=[builtIn(),...model.scenarios].map((t,i)=>{const p=i===0?'builtIn':'scenarios.'+(i-1);return `<div class="scenario-card"><h3>${i===0?'Combined changes':esc(t.name)}</h3><div class="grid">${i>0?input('Scenario name',p+'.name',t.name,{type:'text',max:100}):''}${model.mode==='total'||model.currency==='NGN'?input(model.mode==='total'?'Supplier payment costs more (%)':'Supplier price costs more (%)',p+'.supplier',t.supplier||'0',{unit:'%',hint:'Changes the active supplier amount in naira.'}):input('Exchange rate goes up (%)',p+'.fx',t.fx,{unit:'%',hint:'Applies to '+(model.currency==='USD'?'USD':'CNY')+' supplier/shared rates and costs using them. Independent customs rates stay unchanged.'})}${input('Shipping costs more (%)',p+'.freight',t.freight,{unit:'%'})}${input('Selling price changes (%)',p+'.price',t.price,{unit:'%',hint:'Use a negative change if the selling price goes down.'})}${input('Fewer items can be sold',''+p+'.sellable',t.sellable,{hint:'Leave blank to use your current sellable quantity.'})}${input('Monthly sales change (%)',p+'.sales',t.sales,{unit:'%',hint:'Slower sales changes timing, not what each sale leaves you.'})}</div>${model.mode==='total'?'<p class="help-text">Your naira supplier total is fixed. This scenario changes that amount directly; it does not change currency rates.</p>':''}<div class="scenario-result" id="scenario-result-${i}"></div>${i>0?button('Remove scenario','removescenario:'+(i-1),'link-button'):''}</div>`}).join('');}
function updateScenarioResults(){const base=result();[builtIn(),...model.scenarios].forEach((t,i)=>{const el=document.querySelector('#scenario-result-'+i);if(!el)return;try{const scoped=scopedScenario(model,t);const s=calc(scenario(model,scoped));el.innerHTML=base.salesValid&&s.salesValid&&s.contribution?`<span>What each sale leaves you</span><strong>${money(s.contribution)}</strong><p>Change from your order: ${money(s.contribution.sub(base.contribution!))} · ${fmt(s.margin!.sub(base.margin!),' percentage points')}</p><p>Shipment cash recovery: ${s.units!==null?s.units+' sales':'not recoverable'}${s.recoveryMonths?' · about '+fmt(s.recoveryMonths)+' months':''}${s.units!==null&&!s.achievable?' · cannot recover cash from this batch':''}</p>${s.operating?'<p>Operating estimate: '+money(s.operating)+'</p>':''}`:'<p class="helper-message">Add valid order and scenario details to compare.</p>';}catch(e){el.innerHTML='<p class="helper-message">'+esc((e as Error).message)+'</p>';}})}
function reveal(id:string){const el=document.getElementById(id);if(el instanceof HTMLDetailsElement){el.open=true;openDetails.add(id)}el?.scrollIntoView({block:'start',behavior:'auto'});}
function stepErrors(step:number){const r=result();return Object.keys(r.errors).filter(key=>step===1?['q','s','total','unit','fee','feePct',...(model.currency==='CNY'?[model.advanced?'supplierCny':'cny']:model.currency==='USD'?[model.advanced?'supplierUsd':'usd']:[])].includes(key):step===2?key==='overlap'||model.rows.some(x=>key.startsWith(x.id))||['cny','usd'].includes(key):key==='price'||key.startsWith('sell')||key.startsWith('pct'))}
function markErrors(keys:string[]){for(const k of keys)touched.add(errorKey(k));showErrors();const key=keys.map(errorKey).find(k=>app.querySelector(`[data-key="${k}"]`));if(key){const field=app.querySelector<HTMLElement>(`[data-key="${key}"]`)!;let ancestor=field.parentElement;while(ancestor){if(ancestor instanceof HTMLDetailsElement)ancestor.open=true;ancestor=ancestor.parentElement}field.focus();field.scrollIntoView({block:'center'})}}
function validAction(){const r=result();if(!r.valid){markErrors(Object.keys(r.errors));notify('Check the highlighted figures before saving or downloading. Unknown costs can still be saved as a provisional estimate.');return false}return true}
function download(filename:string,data:BlobPart,type:string){const url=URL.createObjectURL(new Blob([data],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function openModal(title:string,body:string,closeLabel='Close'){const d=document.querySelector<HTMLDialogElement>('#modal')!;const source=document.activeElement as HTMLElement;d.innerHTML=`<h2 id="modal-title">${esc(title)}</h2>${body}${button(closeLabel,'close','quiet')}`;d.onclose=()=>{source?.isConnected?source.focus():app.querySelector<HTMLElement>('[data-action="save"]')?.focus()};if(!d.open)d.showModal();return d}
function confirmChoice(title:string,body:string){return new Promise<boolean>(resolve=>{const d=openModal(title,body+button('Continue','dialogcontinue','primary'));const done=(v:boolean)=>{d.close();resolve(v)};d.querySelector<HTMLElement>('[data-action="dialogcontinue"]')!.onclick=()=>done(true);d.querySelector<HTMLElement>('[data-action="close"]')!.onclick=()=>done(false);d.oncancel=()=>resolve(false)})}
function namePrompt(){return new Promise<string|null>(resolve=>{const d=openModal('Name this calculation',input('Calculation name','saveName',model.name,{type:'text',max:100,placeholder:'For example, October handbag order'})+button('Save calculation','dialogsave','primary'));const done=(v:string|null)=>{d.close();resolve(v)};d.querySelector<HTMLElement>('[data-action="dialogsave"]')!.onclick=()=>{const v=d.querySelector<HTMLInputElement>('input')!.value.trim();if(!v){d.querySelector<HTMLElement>('.error')!.hidden=false;d.querySelector<HTMLElement>('.error')!.textContent='Enter a name for this calculation.';return}done(v)};d.querySelector<HTMLElement>('[data-action="close"]')!.onclick=()=>done(null);d.oncancel=()=>resolve(null)})}
function openHelp(source:HTMLElement){const d=document.querySelector<HTMLDialogElement>('#help-dialog')!;if(d.open)d.close();const label=source.dataset.help!;source.closest('.field,.metric')?.scrollIntoView({block:'center'});d.innerHTML=`<h2 id="help-title">${esc(label)}</h2><p>${esc(helpCopy[label]||'Use the figures for your own order.')}</p><button type="button" data-action="closehelp" aria-label="Close help">Close</button>`;d.onclose=()=>source.isConnected?source.focus():document.querySelector<HTMLElement>('#summary')?.focus();d.style.removeProperty('top');d.style.removeProperty('left');if(innerWidth>760){const rect=source.getBoundingClientRect();d.style.left=Math.min(Math.max(rect.left-140,16),innerWidth-376)+'px';d.style.top=Math.min(rect.bottom+10,innerHeight-230)+'px'}d.showModal();}
async function action(a:string){track(a.split(':')[0]);try{
 if(a==='close'){document.querySelector<HTMLDialogElement>('#modal')!.close();return}
 if(a==='closehelp'){document.querySelector<HTMLDialogElement>('#help-dialog')!.close();return}
 if(a==='example'){if(!model.illustrative&&(model.q||model.total)&&!await confirmChoice('Load example figures?','<p>Your current calculation will be replaced. Save or download it first if needed.</p>'))return;model=illustrative();delete aux.quickPrice;touched.clear();exampleEdited=false;resetOpen();rebuild();notify('You’re viewing example figures.');return}
 if(a==='own'){if((model.q||model.total||exampleEdited)&&!await confirmChoice('Start my own calculation?','<p>This clears the current figures, including example amounts. Saved calculations are kept.</p>'))return;model=fresh();touched.clear();for(const k of Object.keys(aux))delete aux[k];suggested=false;exampleEdited=false;message='';resetOpen();rebuild();app.querySelector<HTMLInputElement>('[data-key="q"]')!.focus();return}
 if(a.startsWith('next:')){const next=Number(a.split(':')[1]),errors=stepErrors(next-1);if(errors.length){markErrors(errors);notify('Check these figures before continuing.');return}message='';reveal('step-'+next);document.querySelector<HTMLElement>('#step-'+next+' summary')?.focus();return}
 if(a.startsWith('back:')){reveal('step-'+a.split(':')[1]);return}
 if(a==='viewresults'){document.querySelector<HTMLElement>('#summary')!.focus();refresh();return}
 if(a==='totalmode'){state().foreignMode=model.mode==='allin'?'allin':'separate';model.mode='total';rebuild('total');return}
 if(a==='foreignmode'){model.mode=state().foreignMode||'separate';openDetails.add('foreign-entry');rebuild('unit');return}
 if(a==='detailedcosts'){switchCosts(model,'detailed');openDetails.add('cost-breakdown');rebuild();return}
 if(a==='simplecosts'){if(!await confirmChoice('Use a single other-cost total?','<p>Your detailed values will be kept but excluded. The previous single total will become active. Review it before using your estimate.</p>'))return;switchCosts(model,'simple');rebuild('rows.'+model.rows.indexOf(other(model))+'.amount');return}
 if(a==='detailedselling'||a==='simpleselling'){if(a==='simpleselling'&&!await confirmChoice('Use one selling-expense total?','<p>Detailed expenses will be kept but excluded. Review the previous total before using your results.</p>'))return;switchSelling(model,a==='detailedselling'?'detailed':'simple');openDetails.add('selling-breakdown');rebuild();return}
 if(a==='sellingcomplete'){state().sellingStatus='entered';rebuild();return}
 if(a==='removeoverlap'){other(model).status='na';state().overlapResolved=true;rebuild();notify('The other-cost total is excluded. Its previous amount is retained.');return}
 if(a==='replaceoverlap'){const o=other(model);const d=openModal('Costs outside your shipping quote','<p>Enter the revised total for charges that are not included in shipping. Do not repeat the same charges.</p>'+input('Remaining import and delivery costs','replacement',o.amount,{unit:'₦'})+button('Use this outside-quote amount','dialogreplace','primary'));d.querySelector<HTMLElement>('[data-action="dialogreplace"]')!.onclick=()=>{try{o.amount=num(d.querySelector<HTMLInputElement>('input')!.value,true).toString();o.status='estimate';state().overlapResolved=true;d.close();rebuild()}catch(e){const er=d.querySelector<HTMLElement>('.error')!;er.hidden=false;er.textContent=(e as Error).message}};return}
 if(a==='reviewdetails'){reveal('step-2');reveal('cost-breakdown');return}
 if(a==='missing'){const r=result();openModal('Some costs are still missing','<p>Your estimate may change when you add them.</p><ul>'+r.missing.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>');return}
 if(a==='advanced'){reveal('step-1');reveal('goods-details');openModal('Advanced settings applied','<ul>'+[model.mode==='allin'?'All-in supplier rate excludes separate fees':'',model.advanced?'Separate supplier/logistics conversion rates':'',state().sellableAdjusted?'Adjusted sellable quantity: '+model.s:'',state().costMode==='detailed'?'Detailed shipment costs, including any tax or quote settings':'',state().sellingMode==='detailed'?'Detailed selling fees, including revenue percentages':'',model.planning?'Sales and business-cost plan':''].filter(Boolean).map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul><p>Review these under Add more details, Advanced import settings and the business-cost plan.</p>');return}
 if(a==='cash'){reveal('cash-details');return}
 if(a==='addcost'||a==='addquote'){if(state().costMode==='simple')switchCosts(model,'detailed');const cost=row(a==='addquote'?'Combined logistics quote':'Other landed cost');cost.category='Other landed cost';model.rows.push(cost);openDetails.add('cost-breakdown');openDetails.add('cost-'+cost.id);if(a==='addquote'){openDetails.add('import-advanced');openDetails.add('tax-'+cost.id)}rebuild();return}
 if(a.startsWith('removecost:')){const id=a.split(':')[1];model.rows=model.rows.filter(r=>r.id!==id);rebuild();return}
 if(a==='shipping'){const e=state(),h=shipping(e.helperMode,e.helper),f=freight(model);if((f.amount||f.status==='included')&&!await confirmChoice('Use this shipping estimate?','<p>This replaces your entered shipping quote. The provider’s final quote takes precedence.</p>'))return;Object.assign(f,{amount:h.amount.toString(),currency:'NGN',basis:'batch',percent:false,status:'estimate',includedIn:undefined});e.appliedHelper=JSON.stringify({mode:e.helperMode,input:e.helper});rebuild();notify('Shipping estimate applied.');return}
 if(a==='loss'){const p=num(aux.loss||'',true);if(p.gte(100))throw Error('Enter a damage percentage below 100%.');model.s=num(model.q,true).mul(new Decimal(1).sub(p.div(100))).floor().toString();state().sellableAdjusted=true;rebuild();notify('Rounded down to '+model.s+' sellable items.');return}
 if(a==='advertising'||a==='returns'){const i=a==='advertising'?1:5;let amount:Decimal;if(a==='advertising'){const n=num(aux.adsSales||'',true);if(!n.isInteger()||n.lte(0))throw Error('Enter completed sales as a whole number above zero.');amount=num(aux.adsSpend||'',true).div(n)}else{const p=num(aux.returnProb||'',true);if(p.gt(100))throw Error('Enter a return rate from 0 to 100%.');amount=p.div(100).mul(num(aux.returnCost||'',true))}if(state().sellingMode==='simple'&&!await confirmChoice('Use detailed selling expenses?','<p>This estimate fills one detailed row. Your single selling-expense total will be kept but excluded. Add the other selling costs in the breakdown.</p>'))return;switchSelling(model,'detailed');model.selling[i].amount=amount.toString();if(i===5)model.selling[i].pct='';openDetails.add('selling-breakdown');rebuild();notify('Estimate applied to '+model.selling[i].label+'. Review the remaining selling expenses.');return}
 if(a==='suggest'||a==='openpricing'){reveal('glance-pricing');document.querySelector<HTMLElement>('[data-key="target"]')?.focus();return}
 if(a==='comparechanges'){reveal('scenarios');return}
 if(a==='allcosts'){reveal('all-costs');return}
 if(a==='assumptions'){openModal('Your order assumptions','<ul>'+[...activeAssumptions(model),...assumptions(model)].map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>');return}
 if(a==='applyprice'){const r=result();if(r.targetPrice&&r.pricingValid){if(r.targetPrice.gt('1000000000000')){notify('The suggested price is above the supported limit. Check your costs or choose a lower target.');return}model.price=r.targetPrice.toString();const field=app.querySelector<HTMLInputElement>('[data-key="price"]');if(field)field.value=model.price;if(model.illustrative)exampleEdited=true;refresh();app.querySelector<HTMLElement>('[data-action="applyprice"]')?.focus({preventScroll:true});notify('Suggested price applied. Your order results have updated.');}return}
 if(a==='addscenario'){if(model.scenarios.length>=3)throw Error('You can add up to three custom scenarios.');model.scenarios.push({...builtIn(),name:'My scenario '+(model.scenarios.length+1)});renderScenarioEditors();updateScenarioResults();return}
 if(a.startsWith('removescenario:')){model.scenarios.splice(Number(a.split(':')[1]),1);renderScenarioEditors();updateScenarioResults();return}
 if(a==='save'||a==='duplicatesave'){if(!validAction())return;const name=await namePrompt();if(name===null)return;model.name=name;const next=[...saves,{id:crypto.randomUUID(),input:structuredClone(model)}];try{localStorage.setItem('zolan-saves-v1',JSON.stringify(next));saves=next;rebuild();notify('Saved on this browser. Download an Excel report to keep a copy of your figures.')}catch{notify('Your browser could not save this calculation. Download an Excel report from More options.')}return}
 if(a==='saved'){openModal('Saved calculations','<p>Saved on this browser. Download an Excel report to keep a copy of your figures.</p>'+saves.map(x=>`<div class="saved-row"><strong>${esc(x.input.name)}</strong><div>${button('Load','load:'+x.id,'secondary')}${button('Duplicate','duplicate:'+x.id,'quiet')}${button('Delete','delete:'+x.id,'quiet')}</div></div>`).join('')+(saves.length?'':'<p>No calculations saved yet.</p>'));return}
 if(a.startsWith('load:')||a.startsWith('duplicate:')){const id=a.split(':')[1];if(!await confirmChoice('Load this calculation?','<p>This replaces current unsaved inputs. Your saved calculations are kept.</p>'))return;model=initialise(validateImport(saves.find(x=>x.id===id)!.input));delete aux.quickPrice;touched.clear();resetOpen();rebuild();if(a.startsWith('duplicate:'))await action('duplicatesave');return}
 if(a.startsWith('delete:')){if(!await confirmChoice('Delete this saved calculation?','<p>Download an Excel report first if you want to keep a copy of the figures.</p>'))return;const next=saves.filter(x=>x.id!==a.split(':')[1]);localStorage.setItem('zolan-saves-v1',JSON.stringify(next));saves=next;await action('saved');return}
 if(a==='xlsx'){if(!validAction())return;download('zolan-import-report.xlsx',excelReport(model,reportContext()),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');notify('Excel report downloaded.');return}
 if(a==='copy'){if(!validAction())return;try{await navigator.clipboard.writeText(summary(model,reportContext()));notify('Results copied.')}catch{openModal('Copy results','<p>Your browser blocked clipboard access. Select and copy this text.</p><textarea aria-label="Calculation results" rows="12">'+esc(summary(model,reportContext()))+'</textarea>')}return}
 if(a==='print'){if(!validAction())return;try{window.print()}catch{notify('Printing is unavailable in this preview. Open the calculator in Chrome to print or save as PDF.')}return}
 }catch(e){notify((e as Error).message)}
}
function resetOpen(){openDetails.clear();openDetails.add('step-1');for(const d of app.querySelectorAll<HTMLDetailsElement>('details'))d.open=d.id==='step-1';}
rebuild();
