import {calc,scenario,stress,type Model} from './engine';
import {experience,combined,scopedScenario} from './experience';
import {money,fmt,esc} from './views';
import {lowerPrice,pricingMessage,activeAssumptions,type ReportContext} from './insights';
export function assumptions(m:Model){const r=calc(m),e=experience(m);return [
 m.illustrative?'You’re viewing example figures. All amounts are illustrative.':'Your entered figures; quote statuses are user-declared.',
 r.missing.length?'Estimate with missing costs. Not entered: '+r.missing.join(', ')+'.':'All selected costs included.',
 'Supplier payment: '+(m.mode==='total'?'full naira total (separate invoice and fees excluded)':m.mode==='allin'?'all-in conversion rate (separate fees excluded)':'converted per-item invoice'+(e.feeEnabled?' plus separate payment fees':'; separate fees not selected'))+'.',
 'Import costs: '+e.costMode+' entry. Selling expenses: '+e.sellingMode+' entry ('+e.sellingStatus+'). Inactive values are retained but excluded.',
 'Contribution means selling price minus economic landed inventory cost and variable selling expenses. Before overhead, financing and business taxes.',
 'Shipment cash recovery assumes immediate customer payment, upfront landing costs and no restocking. Overhead, financing and other cash payments are excluded. Recoverable tax does not reduce shipment cash paid upfront.',
 ...activeAssumptions(m),
 'Manual exchange rates and shipment-specific tax assumptions. This is not an official customs assessment.',
 e.shippingUnsure?'Check what your shipping company includes. Extra charges may still apply.':'',
 e.overlapResolved?'You confirmed that the remaining other costs are outside the combined shipping quote.':'',
 m.advanced?'Separate supplier and logistics rates applied. Customs conversion rates remain independent.':'',
 m.rateNote?'Quote notes: '+m.rateNote:'',m.hs?'Informational HS code: '+m.hs:'',m.rateDate?'Quote date: '+m.rateDate:''
 ].filter(Boolean)}
export function resultValues(m:Model,ctx:ReportContext={}){const r=calc(m);const land=(v:Parameters<typeof money>[0])=>r.landingValid?money(v):'Not available';const sell=(v:Parameters<typeof money>[0])=>r.salesValid?money(v):'Not available';return [
 ...sellingBreakdown(m),['Cost per sellable item',land(r.cost)],['What each sale leaves you',sell(r.contribution)],['Margin after selling expenses',r.salesValid?fmt(r.margin,'%'):'Not available'],['Cash needed for this shipment',land(r.cash)],['Economic landed inventory cost',land(r.econ)],['Potential recoverable import tax',land(r.recovery)],['Gross profit per sale',sell(r.gross)],['Gross margin',r.salesValid?fmt(r.grossMargin,'%'):'Not available'],['Markup',r.salesValid?fmt(r.markup,'%'):'Not available'],['Selling expenses per item',sell(r.variable)],['Full-batch contribution',sell(r.batch)],['Suggested price for target margin'+(m.target?' ('+m.target+'%)':''),r.targetPrice?(r.missing.length?'Provisional: ':'')+money(r.targetPrice):pricingMessage(m)||'No finite suggestion / target not entered'],['Minimum price to cover item and selling costs',r.zeroPrice?(r.missing.length?'Provisional: ':'')+money(r.zeroPrice):pricingMessage(m)||'Not available'],['Sales to recover shipment cash',r.salesValid&&r.units!==null?r.units.toString():'Not available'],['Cash recovery stock limit',r.salesValid&&r.units!==null?r.achievable?'Within sellable stock':'This batch cannot recover the shipment cash at these figures.':'Not available'],['Full-batch cash shortfall',sell(r.shortfall)],['Approximate recovery time',r.recoveryMonths?fmt(r.recoveryMonths,' months'):'Not available'],['Full sell-through estimate',r.sellthrough?fmt(r.sellthrough,' months'):'Not available'],['Forecast units sold',r.planningValid&&r.forecast?r.forecast.toString():'Not available'],['Fixed business costs for plan',r.planningValid?money(r.k):'Not available'],['Estimated operating result',r.planningValid?money(r.operating):'Not available'],['Operating break-even',r.planningValid&&r.breakEven!==null?r.breakEven.toString()+' sales':'Not achievable / no business plan'],...comparisonValues(m,ctx),['Whole-order assumption','All '+m.s+' sellable items sell; selling price and expenses stay unchanged. Before overhead, financing and taxes.']
 ]}
export function summary(m:Model,ctx:ReportContext={}){const r=calc(m);const fields=[['Product name',m.productName||''],['Product description',m.description],['Quantity',m.q],['Sellable items',m.s],['Active supplier payment',money(r.payment)],['Supplier mode',m.mode],['Per-item supplier price',m.mode==='total'?'Retained, inactive':m.unit+' '+m.currency],['Separate supplier fixed fee',m.mode==='separate'&&experience(m).feeEnabled?m.fee:'Not active'],['Separate supplier percentage fee',m.mode==='separate'&&experience(m).feeEnabled?m.feePct:'Not active'],['Selling price',m.price],['Selling expenses status',experience(m).sellingStatus],['Single selling-expense input',experience(m).sellingMode==='simple'?experience(m).sellingTotal:'Retained, inactive'],['Target margin %',m.target],['Expected sales per month',m.planning?m.monthly:'Not active'],['Planning months',m.planning?m.months:'Not active'],['Monthly business costs',m.planning?m.overhead:'Not active'],['One-off business costs',m.planning?m.oneoff:'Not active'],['Shared NGN per yuan',m.cny],['Shared NGN per dollar',m.usd],['Separate supplier NGN per yuan',m.advanced?m.supplierCny:'Not active'],['Separate supplier NGN per dollar',m.advanced?m.supplierUsd:'Not active']];return ['Zolan China import calculation: '+(m.name||m.productName||m.description||'My order'),...assumptions(m),'',...fields.map(([k,v])=>k+': '+(v||'Not entered')),'',...resultValues(m,ctx).map(([k,v])=>k+': '+v),'','Entered costs:',...r.trace.map(x=>`${x.label}: ${x.amount||'Not entered'} ${x.currency}; NGN ${x.ngn}; ${x.reason||x.status}; ${x.base}; recoverable ${x.recover}%; ${x.note}`),'','Selling expense detail:',...m.selling.map(x=>`${x.label}: NGN ${x.amount||'Not selected'} per sale + ${x.pct||'0'}% revenue ${experience(m).sellingMode==='simple'?'(inactive)':''}`)].join('\n')}
export function csv(m:Model,ctx:ReportContext={}){const r=calc(m);const records:unknown[][]=[['Zolan calculation',m.name||m.description],...assumptions(m).map(s=>['Assumption',s]),...resultValues(m,ctx),['Input','Value'],['Quantity ordered',m.q],['Sellable items',m.s],['Supplier mode',m.mode],['Total naira payment (active only in total mode)',m.total],['Per-item supplier price (inactive in total mode)',m.unit],['Supplier currency',m.currency],['Shared CNY rate',m.cny],['Shared USD rate',m.usd],['Separate rates enabled',m.advanced],['Supplier CNY rate',m.supplierCny],['Supplier USD rate',m.supplierUsd],['Supplier fixed fee',m.fee],['Supplier percentage fee',m.feePct],['Fees enabled',experience(m).feeEnabled],['Selling price',m.price],['Selling total',experience(m).sellingTotal],['Target margin',m.target],['Monthly sales',m.monthly],['Planning months',m.months],['Monthly overhead',m.overhead],['One-off business costs',m.oneoff],['Cost','Entered amount','Currency','NGN rate','Raw NGN','Display NGN','Status / exclusion','Base','Recoverable %','Notes'],...r.trace.map(x=>[x.label,x.amount,x.currency,x.rate,r.landingValid?x.ngn:'Not available',r.landingValid?money({toFixed:()=>Number(x.ngn).toFixed(2)}):'Not available',x.reason||x.status,x.base,x.recover,x.note]),['Selling expense','Fixed NGN per sale','Revenue %','Representation'],...m.selling.map(x=>[x.label,x.amount,x.pct,experience(m).sellingMode==='detailed'?'Active detailed rows':'Retained, excluded']),['Scenario','Contribution / sale','Cash recovery sales','Operating result'],...[combined(m),...m.scenarios].map(t=>{try{const s=calc(scenario(m,scopedScenario(m,t)));return[t.name,s.salesValid?money(s.contribution):'Not available',s.salesValid?s.units?.toString():'Not available',money(s.operating)]}catch{return[t.name,'Invalid scenario']}})];const safe=(x:unknown)=>'"'+String(x??'').replace(/^[\s]*[=+\-@]/,"'$&").replaceAll('"','""')+'"';return '\uFEFF'+records.map(x=>x.map(safe).join(',')).join('\r\n')}
export function table(m:Model,all=true){const r=calc(m);const rows=all?r.trace:r.trace.filter(x=>!x.reason.startsWith('Inactive'));return `<div class="table-wrap" role="region" aria-label="Itemised costs" tabindex="0"><table><thead><tr><th>Cost</th><th>Your amount</th><th>NGN total</th><th>What is included</th></tr></thead><tbody><tr><td>Supplier payment</td><td>${m.mode==='total'?esc(m.total)+' NGN':esc(r.invoice)+' '+m.currency}</td><td>${r.landingValid?money(r.payment):'Not available'}</td><td>${m.mode==='total'?'Includes supplier-payment fees':m.mode==='allin'?'All-in conversion rate':'Converted invoice; separately enabled fees'}</td></tr>${rows.map(x=>`<tr class="${x.reason?'muted-row':''}"><td>${esc(x.label)}</td><td>${esc(x.amount||'Not entered')} ${esc(x.currency)}</td><td>${x.reason==='I don’t know yet'?'Not entered':r.landingValid?money({toFixed:()=>Number(x.ngn).toFixed(2)}):'Not available'}</td><td>${esc(x.reason||x.status)}${x.base?'<br><small>'+esc(x.base)+'</small>':''}${!x.reason&&x.currency!=='NGN'&&x.currency!=='%'?'<br><small>NGN conversion rate '+esc(x.rate)+'</small>':''}${Number(x.recover)>0?'<br><small>'+esc(x.recover)+'% recoverable tax</small>':''}${x.note?'<br><small>'+esc(x.note)+'</small>':''}</td></tr>`).join('')}</tbody></table></div>`}
export function printReport(m:Model,ctx:ReportContext={}){const r=calc(m);return `<div class="report-brand">Zolan · China import calculation</div><h1>${esc(m.name||m.productName||m.description||'My import plan')}</h1><p>${new Date().toLocaleDateString('en-GB',{timeZone:'Africa/Lagos'})}</p>${assumptions(m).map(s=>'<p>'+esc(s)+'</p>').join('')}<h2>Results</h2><table><tbody>${resultValues(m,ctx).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${esc(v)}</td></tr>`).join('')}</tbody></table><h2>Inputs and assumptions</h2><pre>${esc(summary(m,ctx).split('Entered costs:')[0])}</pre><h2>Every import cost</h2>${table(m)}<h2>Selling expenses</h2><table><thead><tr><th>Expense</th><th>Fixed NGN per sale</th><th>Revenue %</th><th>Status</th></tr></thead><tbody>${m.selling.map(x=>`<tr><td>${esc(x.label)}</td><td>${esc(x.amount||'Not selected')}</td><td>${esc(x.pct||'0')}</td><td>${experience(m).sellingMode==='detailed'?'Detailed entry':'Retained, inactive'}</td></tr>`).join('')}</tbody></table><h2>Scenarios</h2>${[combined(m),...m.scenarios].map(t=>{try{const s=calc(scenario(m,scopedScenario(m,t)));return `<h3>${esc(t.name)}</h3><p>Contribution per sale: ${s.salesValid?money(s.contribution):'Not available'}; cash recovery: ${s.units?.toString()||'Not available'} sales. Inputs: ${esc(scenarioAssumptions(m,t))}</p>`}catch{return '<p>Scenario has invalid inputs.</p>'}}).join('')}<p>Contribution is before overhead, financing and business taxes. No live rates or official customs assessment.</p>`}

function scenarioAssumptions(m:Model,t:import('./engine').Scenario){return [(m.mode==='total'||m.currency==='NGN'?'Supplier amount change: '+(t.supplier||'0')+'%':'Exchange-rate change: '+t.fx+'% for '+m.currency+' supplier/shared rates'), 'Shipping change: '+t.freight+'%', 'Selling-price change: '+t.price+'%', 'Sellable items: '+(t.sellable||m.s), 'Monthly-sales change: '+t.sales+'%', 'Independent customs rates stay unchanged.'].join('; ')}

export function sellingBreakdown(m:Model):[string,string][]{const r=calc(m);if(!r.salesValid||!r.contribution)return [['Selling-price breakdown','Add valid order details and a selling price.']];return [['Selling price',money(r.p)],['Cost to buy and land it','−'+money(r.cost.abs())],['Selling expenses','−'+money(r.variable!.abs())],[r.contribution.lt(0)?'Shortfall per sale':'Left before overhead and taxes',money(r.contribution.abs())]];}
function comparisonValues(m:Model,ctx:ReportContext):[string,string][]{if(!('alternativePrice' in ctx))return [];const b=calc(m),q=lowerPrice(m,ctx.alternativePrice);if(!b.salesValid||!b.contribution||!q.result?.salesValid||!q.result.contribution||!q.difference)return [['Lower-price comparison',q.error||'Not available']];return [['Comparison assumption',ctx.alternativePrice===undefined?'10% below current selling price; not applied':'User-entered alternative price; not applied'],['Comparison current selling price',money(b.p)],['Comparison alternative price',money(q.result.p)],['Comparison current contribution',money(b.contribution)],['Comparison alternative contribution',money(q.result.contribution)],['Comparison difference per sale',(q.difference.lt(0)?'−':q.difference.gt(0)?'+':'')+money(q.difference.abs())],['Comparison assumption','Percentage fees recalculated. Landed cost and fixed selling expenses unchanged.']];}
