import test from 'node:test';
import assert from 'node:assert/strict';
import {Window,type HTMLElement,type HTMLInputElement,type HTMLDetailsElement,type HTMLDialogElement} from 'happy-dom';
import {readdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';

test('production UI: blank, progressive flow, modes, help, saves, scenarios and reset',async()=>{
 const w=new Window({url:'http://127.0.0.1:5174/'});
 for(const k of ['window','document','navigator','localStorage','HTMLElement','HTMLInputElement','HTMLSelectElement','HTMLDetailsElement','HTMLDialogElement','MutationObserver','Event','MouseEvent','FocusEvent','innerWidth','innerHeight'])Object.defineProperty(globalThis,k,{value:k==='window'?w:(w as any)[k],configurable:true});
 w.HTMLElement.prototype.scrollIntoView=()=>{};
 w.document.body.innerHTML='<div id="app"></div>';
 const js=(await readdir(new URL('../dist/assets/',import.meta.url))).find(n=>n.endsWith('.js'))!;
 await import(pathToFileURL(new URL('../dist/assets/'+js,import.meta.url).pathname).href);
 const d=w.document;
 const click=async(a:string)=>{const el=d.querySelector<HTMLElement>('[data-action="'+a+'"]');assert.ok(el,a);el.click();await new Promise(r=>setTimeout(r,0));};
 const fill=(key:string,value:string)=>{const el=d.querySelector<HTMLInputElement>('[data-key="'+key+'"]');assert.ok(el,key);el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));};
 const summary=()=>d.querySelector('#summary')!.textContent!;
 assert.equal(d.querySelectorAll('.step-section').length,3);
 assert.equal(d.querySelectorAll('[data-action="json"], [data-action="import"], [data-action="csv"]').length,0);
 assert.equal(d.querySelectorAll('[data-action="xlsx"]').length,2);
 assert.equal(d.querySelectorAll('[aria-invalid="true"]').length,0);
 assert.match(summary(),/Add your order details to get started/);
 assert.equal((d.querySelector('#step-1') as HTMLDetailsElement).open,true);
 assert.equal((d.querySelector('#step-2') as HTMLDetailsElement).open,false);
 assert.equal((d.querySelector('[data-key="total"]') as HTMLInputElement).readOnly,false);
 await click('next:2');assert.ok(d.querySelector('[data-key="q"][aria-invalid="true"]'));
 fill('q','100');fill('total','880000');
 assert.match(summary(),/₦8,800/);assert.match(summary(),/missing costs/);
 await click('next:2');assert.equal((d.querySelector('#step-2') as HTMLDetailsElement).open,true);
 fill('price','25000');fill('experience.sellingTotal','4000');assert.match(summary(),/₦12,200/);
 fill('total','-1');assert.doesNotMatch(summary(),/₦8,800/);fill('total','880000');
 fill('unit','40');fill('cny','220');await click('foreignmode');assert.match(summary(),/₦8,800/);
 await click('totalmode');assert.match(summary(),/₦8,800/);
 const help=d.querySelector<HTMLElement>('[data-help="Total supplier payment"]')!;help.click();
 assert.equal((d.querySelector('#help-dialog') as HTMLDialogElement).open,true);assert.match(d.querySelector('#help-dialog')!.textContent!,/full naira amount/);
 await click('closehelp');assert.equal((d.querySelector('#help-dialog') as HTMLDialogElement).open,false);
 await click('example');await click('dialogcontinue');assert.match(summary(),/₦16,600/);assert.match(summary(),/₦4,400/);assert.match(d.body.textContent!,/You’re viewing example figures/);
 assert.match(summary(),/Your order at a glance/);assert.match(summary(),/Minimum price to cover/);assert.match(summary(),/₦20,600/);assert.doesNotMatch(summary(),/each item costs about/);
 const target=d.querySelector<HTMLInputElement>('[data-key="target"]')!;target.focus();fill('target','20');assert.equal(d.activeElement,target);assert.match(d.querySelector('#price-suggestion')!.textContent!,/For a 20% margin, sell at ₦25,750/);
 const lower=d.querySelector<HTMLDetailsElement>('#glance-lower')!;lower.open=true;lower.dispatchEvent(new w.Event('toggle'));assert.match(d.querySelector('#glance-lower-result')!.textContent!,/₦1,900/);assert.match(d.querySelector('#print-report')!.textContent!,/Comparison alternative price/);
 fill('aux.quickPrice','18000');assert.match(d.querySelector('#glance-lower-result')!.textContent!,/short by ₦2,600/);assert.equal((d.querySelector('[data-key="price"]') as HTMLInputElement).value,'25000');
 await click('applyprice');assert.equal(d.activeElement,d.querySelector('[data-action="applyprice"]'));assert.equal((d.querySelector('[data-key="price"]') as HTMLInputElement).value,'25750');assert.match(summary(),/20.00%/);assert.match(d.querySelector('#notice')!.textContent!,/applied/);
 fill('price','10000');assert.match(summary(),/Loss per sale/);assert.match(d.querySelector('#glance-breakdown')!.textContent!,/Shortfall per sale/);assert.match(d.querySelector('#glance-order-result')!.textContent!,/shortfall/);fill('price','25000');
 const ids=Array.from(d.querySelectorAll('[id]')).map(e=>e.id);assert.equal(new Set(ids).size,ids.length);
 for(const el of d.querySelectorAll('input[data-key],select[data-key]'))assert.ok(d.querySelector('label[for="'+el.id+'"]')||el.closest('label'),'label '+el.id);
 fill('builtIn.freight','25');await click('save');fill('saveName','UI test plan');await click('dialogsave');
 const saved=JSON.parse(w.localStorage.getItem('zolan-saves-v1')!);assert.equal(saved[0].input.combinedScenario.freight,'25');assert.equal(saved[0].input.experience.costMode,'detailed');assert.equal(saved[0].input.name,'UI test plan');
 assert.match(d.querySelector('#print-report')!.textContent!,/Before overhead/);assert.match(d.querySelector('#print-report')!.textContent!,/25/);
 await click('own');await click('dialogcontinue');assert.doesNotMatch(summary(),/₦16,600/);assert.equal((d.querySelector('[data-key="q"]') as HTMLInputElement).value,'');assert.doesNotMatch(d.body.textContent!,/You’re viewing example figures/);
 await click('saved');await click('load:'+saved[0].id);await click('dialogcontinue');assert.match(summary(),/₦16,600/);assert.equal((d.querySelector('[data-key="builtIn.freight"]') as HTMLInputElement).value,'25');
 await w.happyDOM.close();
});
