// Compile the same calculator for an existing email-gated React application.
// Usage: npm run build:access -- /absolute/path/to/access-project
import {execFileSync} from 'node:child_process';
import {readFileSync,writeFileSync,cpSync,mkdirSync,existsSync} from 'node:fs';
import {resolve} from 'node:path';
const target=process.argv[2];
if(!target||!existsSync(resolve(target,'app/tools/china-import-profit-calculator/calculate/page.tsx')))throw Error('Provide the existing email-access project directory.');
execFileSync(process.execPath,['node_modules/typescript/bin/tsc','--noEmit'],{stdio:'inherit'});
execFileSync(process.execPath,['node_modules/vite/bin/vite.js','build','--base=/calculator-assets/','--outDir=dist-access'],{stdio:'inherit'});
const dest=resolve(target,'public/calculator-assets');mkdirSync(dest,{recursive:true});
cpSync('dist-access/assets',resolve(dest,'assets'),{recursive:true});
// The document is rendered only by the authenticated server route. No public HTML entry.
const html=readFileSync('dist-access/index.html','utf8');
writeFileSync(resolve(target,'app/calculator-document.ts'),'// Generated by the shared Zolan calculator build.\nexport const calculatorDocument = '+JSON.stringify(html)+';\n');
writeFileSync(resolve(target,'app/calculator.tsx'),`"use client";
import {calculatorDocument} from "./calculator-document";
export default function Calculator(){return <iframe title="Zolan China import calculator" srcDoc={calculatorDocument} style={{display:"block",width:"100%",height:"100dvh",border:0,background:"#f4f7fa"}}/>;}
`);
console.log('Updated the calculator behind the existing access route. Landing, cookies and access APIs were preserved.');
